### ISSUE TITLE
I

### ISSUE THREAD

**Issue by TInaZhouzzzzz** [wenwei202/terngrad#10]
I try in caffe.
 Alexnet ,single worker. I do like this: 
1). ternarize  all  gradients in convolution layers and fc layers
2). ternarizing method: a). m=diff/diff_max(among one layer), b) generate random num : rand_blob_ ∈（0，1）    c).compare m and rand_blob_ : if( m >rand_blob_[i] ) diff_[i] = diff_max; else diff_[i]=0

when training , first 500 epoch,it behaves well ,but than,it keep  from ~6.1 to ~6.7  in the later 5000 iters, then I stop training.

Because I want to train in resnet or vgg or other nets , I want to know whether the code I change is right.
Thanks！

**Comment by wenwei202** [comment]
if( m[i] **<** rand_blob_[i] ) diff_[i] = diff_max; 

and signs of gradients should be considered. Please refer to our paper for more details.
