### ISSUE TITLE
Error: double free or corruption (!prev): 0x0000000000c6c780

### ISSUE THREAD

**Issue by TInaZhouzzzzz** [wenwei202/terngrad#4]
when I run Imagenet， Error in `/home/anaconda2/envs/tensorflow/bin/python': : double free or corruption (!prev): 0x0000000000c6c780

I do such step :
  i). Download and generate ImageNet TFRecord
     I do it like you say and get TFrecord 1024 train and 128 validation
   ii). Build and run ImageNet
 I do it like you say:
cd ${TERNGRAD_ROOT}/terngrad
bazel build inception/imagenet_train
bazel build inception/imagenet_eval

bazel-bin/inception/imagenet_train \
--optimizer momentum \
--net alexnet \
--image_size 224 \
--num_gpus 2 \
--batch_size 256 \
--train_dir /tmp/imagenet_train \
--data_dir ~/dataset/imagenet-data/

but at this step ,
    Error in `/home/anaconda2/envs/tensorflow/bin/python': : double free or corruption (!prev): 0x0000000000c6c780.
 
I would appreciate for your answer. thank you

**Comment by wenwei202** [comment]
Did you try to `bazel clean`, and built from scratch?

**Comment by TInaZhouzzzzz** [comment]
I try to bazel clean , and then do 
bazel build inception/imagenet_train
bazel build inception/imagenet_eval

bazel-bin/inception/imagenet_train 
--optimizer momentum 
--net alexnet 
--image_size 224 
--num_gpus 2 
--batch_size 256 
--train_dir /tmp/imagenet_train 
--data_dir ~/dataset/imagenet-data/'

still the same error

**Comment by wenwei202** [comment]
[This](https://github.com/tensorflow/tensorflow/issues/6968) might help. Seems it would not being a problem of terngrad, which has only python code. Please try to reinstall your tensorflow.
