### ISSUE TITLE
Can't find the code of formula (1) of Terngrad paper

### ISSUE THREAD

**Issue by yaomingshr** [wenwei202/terngrad#7]
I'm interested in terngrad and want to try it in my own project. I want to make sure the meaning of ternarize in your paper, but I can't find it in code.

Can u specific it for me? Which part of code is for  formula (1) of your Terngrad paper?

**Comment by wenwei202** [comment]
The key implementation is [here](https://github.com/wenwei202/terngrad/blob/master/terngrad/inception/inception_train.py#L381).

To read the code of terngrad, generally, you can assume `FLAGS.grad_bits==1`, `FLAGS. clip_factor==2.5`, and [others](https://github.com/wenwei202/terngrad/blob/master/terngrad/inception/inception_train.py#L88-L93) by default.
