### ISSUE TITLE
Communication in distributed training

### ISSUE THREAD

**Issue by zuowang** [wenwei202/terngrad#9]
@wenwei202 
Could help me to understand your code?
The steps to ternarize gradient is as below:
1. Find the scaler for a layer, ex. 0.77370787
2. Turn the gradient into (0, -scaler, scaler) by formula(1), ex.
array([[ 0.        ,  -0.77370787,  0.77370787,  0.77370787,  0.77370787],
           [ 0.        ,  0.        ,  0.        ,  0.        ,  0.77370787],
           [ 0.        ,  0.        ,  -0.77370787,  0.77370787,  0.77370787],
           [ 0.        ,  0.77370787,  0.        ,  0.77370787,  0.        ],
           [ 0.77370787,  0.        ,  0.        ,  0.77370787,  0.        ]], dtype=float32)
3. encode gradient into scaler and 3-level array
4. Send scaler and 3-level array to parameter server

Is that right? Thanks a lot!!

**Comment by wenwei202** [comment]
Correct

**Comment by zuowang** [comment]
Thanks!
